### ISSUE TITLE
Attach participants to a challenge

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/stackoverflowchallenge#17]
When you edit a challenge you can see a label 'Teilnehmer'.
Under this label (empty section) there should be a component that manages the participants who should be associated with the challenge.
The implementation is not defined, but I thought about a list with checkboxes whether the participant participates in this challenge or not.

**Comment by MaxReiser** [comment]
All components are implemented but the whole process can't be executetd due to invinite recoursion caused by javax.ws.rs.ProcessingException: RESTEASY008205: JSON Binding serialization error java.lang.StackOverflowError
