### ISSUE TITLE
Database migration with flyway

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/stackoverflowchallenge#2]
First Steps: https://flywaydb.org/getstarted/how
Maven config: https://flywaydb.org/getstarted/firststeps/maven

Add sql files to so-challenge-backend
Use [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html) to create a zip file which contains the sql files.

**Comment by MaxReiser** [comment]
committed but should be reviewd by @hwirnsberger
